import { DollarSign } from "lucide-react";
import { fetchUsdRates } from "../currency-rates";
import type { CurrencyConverterDefinition } from "../types";

// Every currency code the rate source (open.er-api.com) publishes a rate
// for, so nothing is arbitrarily left out — label is the ISO 4217 currency
// name, symbol is the 3-letter code (kept consistent since most of these
// don't have a widely-recognized glyph, and several share the same one,
// e.g. "$").
const units = [
  { id: "AED", label: "UAE Dirham" },
  { id: "AFN", label: "Afghan Afghani" },
  { id: "ALL", label: "Albanian Lek" },
  { id: "AMD", label: "Armenian Dram" },
  { id: "ANG", label: "Netherlands Antillean Guilder" },
  { id: "AOA", label: "Angolan Kwanza" },
  { id: "ARS", label: "Argentine Peso" },
  { id: "AUD", label: "Australian Dollar" },
  { id: "AWG", label: "Aruban Florin" },
  { id: "AZN", label: "Azerbaijani Manat" },
  { id: "BAM", label: "Bosnia-Herzegovina Convertible Mark" },
  { id: "BBD", label: "Barbadian Dollar" },
  { id: "BDT", label: "Bangladeshi Taka" },
  { id: "BGN", label: "Bulgarian Lev" },
  { id: "BHD", label: "Bahraini Dinar" },
  { id: "BIF", label: "Burundian Franc" },
  { id: "BMD", label: "Bermudan Dollar" },
  { id: "BND", label: "Brunei Dollar" },
  { id: "BOB", label: "Bolivian Boliviano" },
  { id: "BRL", label: "Brazilian Real" },
  { id: "BSD", label: "Bahamian Dollar" },
  { id: "BTN", label: "Bhutanese Ngultrum" },
  { id: "BWP", label: "Botswanan Pula" },
  { id: "BYN", label: "Belarusian Ruble" },
  { id: "BZD", label: "Belize Dollar" },
  { id: "CAD", label: "Canadian Dollar" },
  { id: "CDF", label: "Congolese Franc" },
  { id: "CHF", label: "Swiss Franc" },
  { id: "CLF", label: "Chilean Unit of Account (UF)" },
  { id: "CLP", label: "Chilean Peso" },
  { id: "CNH", label: "Chinese Yuan (Offshore)" },
  { id: "CNY", label: "Chinese Yuan" },
  { id: "COP", label: "Colombian Peso" },
  { id: "CRC", label: "Costa Rican Colón" },
  { id: "CUP", label: "Cuban Peso" },
  { id: "CVE", label: "Cape Verdean Escudo" },
  { id: "CZK", label: "Czech Koruna" },
  { id: "DJF", label: "Djiboutian Franc" },
  { id: "DKK", label: "Danish Krone" },
  { id: "DOP", label: "Dominican Peso" },
  { id: "DZD", label: "Algerian Dinar" },
  { id: "EGP", label: "Egyptian Pound" },
  { id: "ERN", label: "Eritrean Nakfa" },
  { id: "ETB", label: "Ethiopian Birr" },
  { id: "EUR", label: "Euro" },
  { id: "FJD", label: "Fijian Dollar" },
  { id: "FKP", label: "Falkland Islands Pound" },
  { id: "FOK", label: "Faroese Króna" },
  { id: "GBP", label: "British Pound" },
  { id: "GEL", label: "Georgian Lari" },
  { id: "GGP", label: "Guernsey Pound" },
  { id: "GHS", label: "Ghanaian Cedi" },
  { id: "GIP", label: "Gibraltar Pound" },
  { id: "GMD", label: "Gambian Dalasi" },
  { id: "GNF", label: "Guinean Franc" },
  { id: "GTQ", label: "Guatemalan Quetzal" },
  { id: "GYD", label: "Guyanaese Dollar" },
  { id: "HKD", label: "Hong Kong Dollar" },
  { id: "HNL", label: "Honduran Lempira" },
  { id: "HRK", label: "Croatian Kuna" },
  { id: "HTG", label: "Haitian Gourde" },
  { id: "HUF", label: "Hungarian Forint" },
  { id: "IDR", label: "Indonesian Rupiah" },
  { id: "ILS", label: "Israeli New Shekel" },
  { id: "IMP", label: "Isle of Man Pound" },
  { id: "INR", label: "Indian Rupee" },
  { id: "IQD", label: "Iraqi Dinar" },
  { id: "IRR", label: "Iranian Rial" },
  { id: "ISK", label: "Icelandic Króna" },
  { id: "JEP", label: "Jersey Pound" },
  { id: "JMD", label: "Jamaican Dollar" },
  { id: "JOD", label: "Jordanian Dinar" },
  { id: "JPY", label: "Japanese Yen" },
  { id: "KES", label: "Kenyan Shilling" },
  { id: "KGS", label: "Kyrgystani Som" },
  { id: "KHR", label: "Cambodian Riel" },
  { id: "KID", label: "Kiribati Dollar" },
  { id: "KMF", label: "Comorian Franc" },
  { id: "KRW", label: "South Korean Won" },
  { id: "KWD", label: "Kuwaiti Dinar" },
  { id: "KYD", label: "Cayman Islands Dollar" },
  { id: "KZT", label: "Kazakhstani Tenge" },
  { id: "LAK", label: "Laotian Kip" },
  { id: "LBP", label: "Lebanese Pound" },
  { id: "LKR", label: "Sri Lankan Rupee" },
  { id: "LRD", label: "Liberian Dollar" },
  { id: "LSL", label: "Lesotho Loti" },
  { id: "LYD", label: "Libyan Dinar" },
  { id: "MAD", label: "Moroccan Dirham" },
  { id: "MDL", label: "Moldovan Leu" },
  { id: "MGA", label: "Malagasy Ariary" },
  { id: "MKD", label: "Macedonian Denar" },
  { id: "MMK", label: "Myanma Kyat" },
  { id: "MNT", label: "Mongolian Tugrik" },
  { id: "MOP", label: "Macanese Pataca" },
  { id: "MRU", label: "Mauritanian Ouguiya" },
  { id: "MUR", label: "Mauritian Rupee" },
  { id: "MVR", label: "Maldivian Rufiyaa" },
  { id: "MWK", label: "Malawian Kwacha" },
  { id: "MXN", label: "Mexican Peso" },
  { id: "MYR", label: "Malaysian Ringgit" },
  { id: "MZN", label: "Mozambican Metical" },
  { id: "NAD", label: "Namibian Dollar" },
  { id: "NGN", label: "Nigerian Naira" },
  { id: "NIO", label: "Nicaraguan Córdoba" },
  { id: "NOK", label: "Norwegian Krone" },
  { id: "NPR", label: "Nepalese Rupee" },
  { id: "NZD", label: "New Zealand Dollar" },
  { id: "OMR", label: "Omani Rial" },
  { id: "PAB", label: "Panamanian Balboa" },
  { id: "PEN", label: "Peruvian Sol" },
  { id: "PGK", label: "Papua New Guinean Kina" },
  { id: "PHP", label: "Philippine Peso" },
  { id: "PKR", label: "Pakistani Rupee" },
  { id: "PLN", label: "Polish Złoty" },
  { id: "PYG", label: "Paraguayan Guarani" },
  { id: "QAR", label: "Qatari Rial" },
  { id: "RON", label: "Romanian Leu" },
  { id: "RSD", label: "Serbian Dinar" },
  { id: "RUB", label: "Russian Ruble" },
  { id: "RWF", label: "Rwandan Franc" },
  { id: "SAR", label: "Saudi Riyal" },
  { id: "SBD", label: "Solomon Islands Dollar" },
  { id: "SCR", label: "Seychellois Rupee" },
  { id: "SDG", label: "Sudanese Pound" },
  { id: "SEK", label: "Swedish Krona" },
  { id: "SGD", label: "Singapore Dollar" },
  { id: "SHP", label: "Saint Helena Pound" },
  { id: "SLE", label: "Sierra Leonean Leone" },
  { id: "SLL", label: "Sierra Leonean Leone (Old)" },
  { id: "SOS", label: "Somali Shilling" },
  { id: "SRD", label: "Surinamese Dollar" },
  { id: "SSP", label: "South Sudanese Pound" },
  { id: "STN", label: "São Tomé & Príncipe Dobra" },
  { id: "SYP", label: "Syrian Pound" },
  { id: "SZL", label: "Swazi Lilangeni" },
  { id: "THB", label: "Thai Baht" },
  { id: "TJS", label: "Tajikistani Somoni" },
  { id: "TMT", label: "Turkmenistani Manat" },
  { id: "TND", label: "Tunisian Dinar" },
  { id: "TOP", label: "Tongan Paʻanga" },
  { id: "TRY", label: "Turkish Lira" },
  { id: "TTD", label: "Trinidad & Tobago Dollar" },
  { id: "TVD", label: "Tuvaluan Dollar" },
  { id: "TWD", label: "New Taiwan Dollar" },
  { id: "TZS", label: "Tanzanian Shilling" },
  { id: "UAH", label: "Ukrainian Hryvnia" },
  { id: "UGX", label: "Ugandan Shilling" },
  { id: "USD", label: "US Dollar" },
  { id: "UYU", label: "Uruguayan Peso" },
  { id: "UZS", label: "Uzbekistani Som" },
  { id: "VES", label: "Venezuelan Bolívar" },
  { id: "VND", label: "Vietnamese Dong" },
  { id: "VUV", label: "Vanuatu Vatu" },
  { id: "WST", label: "Samoan Tala" },
  { id: "XAF", label: "Central African CFA Franc" },
  { id: "XCD", label: "East Caribbean Dollar" },
  { id: "XCG", label: "Caribbean Guilder" },
  { id: "XDR", label: "Special Drawing Rights" },
  { id: "XOF", label: "West African CFA Franc" },
  { id: "XPF", label: "CFP Franc" },
  { id: "YER", label: "Yemeni Rial" },
  { id: "ZAR", label: "South African Rand" },
  { id: "ZMW", label: "Zambian Kwacha" },
  { id: "ZWG", label: "Zimbabwe Gold" },
  { id: "ZWL", label: "Zimbabwean Dollar (Old)" },
].map((u) => ({ ...u, symbol: u.id }));

const currency: CurrencyConverterDefinition = {
  name: "Currency Converter",
  slug: "currency",
  description:
    "Convert between world currencies — including Nepalese Rupee and 160+ others — using live exchange rates.",
  shortDescription: "Convert 160+ world currencies at live rates.",
  icon: DollarSign,
  keywords: [
    "currency converter",
    "exchange rate calculator",
    "usd to eur",
    "usd to npr",
    "nepali currency converter",
    "forex converter",
  ],
  kind: "currency",
  isPopular: true,
  units,
  defaultFromUnit: "USD",
  defaultToUnit: "EUR",
  fetchRates: fetchUsdRates,
  faq: [
    {
      question: "Where do the exchange rates come from?",
      answer:
        "Rates are sourced from ExchangeRate-API's free, open-access endpoint, covering over 160 currencies. Rates refresh roughly every 6 hours on this page (the underlying data updates about once a day).",
    },
    {
      question: "Are these rates suitable for real transactions?",
      answer:
        "These are reference (mid-market) rates for informational purposes. Banks and payment providers add their own margin, so the rate you actually get when exchanging money will differ.",
    },
    {
      question: "Is Nepalese Rupee (NPR) supported?",
      answer: "Yes — NPR is included, along with 160+ other world currencies.",
    },
  ],
  relatedSlugs: ["length", "weight"],
};

export default currency;
